[package]
name = "spit"
version = "0.1.0"
authors = ["Theodore Bauer <ted@commure.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rust-ini = "0.17"
sha-1 = "0.9.8"
libz-sys = "1.1.3"